# Generated by Django 4.1.7 on 2023-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_genre_alter_book_patrons_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('R', 'RESERVED')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
